[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[general]
import = [
    "/Users/dagu/.config/alacritty/alacritty-theme/themes/catppuccin.toml",
    "/Users/dagu/.dotfiles/alacritty/.config/alacritty/themes/themes/catppuccin_mocha.toml",
]
live_config_reload = true

[[keyboard.bindings]]
chars = '\x1b[1;5I'
key = "Tab"
mods = "Control"

[[keyboard.bindings]]
chars = '\x1b[1;6I'
key = "Tab"
mods = "Control|Shift"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1

[window.padding]
x = 25
y = 20
