
[ env ]
TERM = "xterm-256color"

[keyboard]
bindings = [
   { key= "Tab",        mods= "Control",        chars= "\\x1b[1;5I" },
    { key= "Tab",        mods= "Control|Shift",  chars= "\\x1b[1;6I" },
]

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1 

[window.padding]
x = 25
y = 20

[font]
size = 14.0

[general]
live_config_reload = true

# import = ["~/.config/alacritty/rose-pine-moon.toml"]
import = ["~/.config/alacritty/themes/themes/catppuccin.toml"]

[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"
