#!/bin/bash
#
# Author: Mohamed Bakari
# Description: Simple mpd status script to show current song title and album
# Dependencies: This requires mpd, ncmpcpp and mpc installed

. $HOME/.config/polybar/lemonbar_config

# Check if mpd daemon is running
mpd_status=$(pgrep -c mpd)
if [[  "$mpd_status" == 1 ]];then
        echo "MPD..Offline"
else    
        # Check ncmpcpp status
        ncmpcpp_status=$(mpc status | wc -l)
        if [[ "$ncmpcpp_status" == 1 ]];then
                echo "%{F$BLUE}Stopped%{F-}"
        else
                              
                title=$(ncmpcpp --current-song={%t} 2> /dev/null)  # Set title
                album=$(ncmpcpp --current-song={%b} 2> /dev/null)  # Set album
                title_len=${#title}  # Get the length of the title

                if [[ $title_len > 30 ]];then  # If the title is more than 30 characters
                        title=$(echo $title | cut -b 1-30) # trim of some of them
                        echo "%{F$FG}$title%{F-} %{F$RED}-%{F-} %{F$FG}$album%{F-}"
                else
                        echo "%{F$FG}$title%{F-} %{F$RED}-%{F-} %{F$FG}$album%{F-}"
                fi
               
        fi
fi
