#!/bin/sh

# This is a simple shell script I have created due to lazyness.

SERVICE_STATUS=$(sudo systemctl status docker | grep "Active" | awk '{print $2}')

# If an argument is provided then start the service, else echo error message
if [[ SERVICE_STATUS="Active" ]]; then
	echo "$1 is all ready running"
elif [[ ! -z "$1" ]]; then
	sudo systemctl start $1
else
	echo "Which service do you want me to run?"
fi
